server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: none
    sql:
      init:
        mode: always

  application:
    name: message-monitoring

  zipkin:
    enabled: ${ZIPKIN_MODE:false}

  rabbitmq:
    host: "localhost"
    port: 5672

rabbit:
  queue:
    common-monitoring-queue: "common_monitoring"
    daily-queue: "daily_queue"
    alert-queue: "alert_queue"
    error-queue: "error_queue"
